= adbook

== Welcome

https://github.com/toyboot4e/adbook[adbook repository]

=== Introduction

`adbook` is a tool for building book-like webpages. Notes:

* {mdbook} vs {adbook}
+
{mdbook} is a better choice in many ways, but {adbook} uses https://asciidoctor.org/docs/what-is-asciidoc/[AsciiDoc] as the source format.

* `asciidoctor` vs `adbook`
+
`asciidoctor` creates single page websites by default, while `adbook` creates multiple page websites.

=== Installation

==== Rust & adbook

If you have https://play.rust-lang.org/[Rust], `adbook` is available via Crates.io:

[source,bash]
----
$ cargo install adbook # -> $HOME/.cargo/bin
----

==== Ruby & Asciidoctor

You need Ruby and some package manager. I recommend https://rvm.io/[RVM] because programs installed with it ran faster than that were with `rbenv` (somehow).

Then let's get Asciidoctor gems:

[source,bash]
----
$ gem install asciidoctor
$ gem install asciidoctor-diagram
----

We're ready!

== Usage

=== New project

Let's create a new book:

[source,bash]
----
$ adbook init my-book
Initialized a new adbook project at my-book
----

And see the files in it:

[source,bash]
----
$ tree my-book/ -L 2
my-book/
├── book.ron // <1>
├── site // <2>
└── src // <3>
    ├── article.adoc
    ├── index.adoc
    ├── index.ron // <4>
    └── static

3 directories, 4 files
----
<1> `book.ron` is the root configuration file.
<2> `site` is the default output directory.
<3> `src` is the source file directory.
<4> `index.ron` is very similar to `mod.rs`.

=== Configuration files

Configruation files are in https://github.com/ron-rs/ron[Ron] format.

* `book.ron` (maps to https://docs.rs/adbook/latest/adbook/book/config/struct.BookRon.html[BookRon])
+
It declares books information and build configuration.

* `index.ron` (maps to https://docs.rs/adbook/latest/adbook/book/config/struct.IndexRon.html[IndexRon])
+
It lists the source files in the directory.

For details, check out the https://github.com/toyboot4e/adbook/tree/gh-pages[source files] of this demo.

=== Build

Let's get into the book directory:

[source,sh]
----
$ cd my-book
----

We can build our book as this:

[source,sh]
----
$ # Build the book (using the cached files in `.adbook-cache/`
$ adbook build

$ # Build the book, clearing all the cache.
$ # Use the `-f` option on e.g. adding new files:
$ adbook build --force
----

=== Serving the site

{adbook} does not have `serve` command (yet). Use other commands:

From one shell..

[source,sh]
----
$ python3 -m http.server 8050
----

From another shell..

[source,sh]
----
$ watchexec -e adoc,ron -w src adbook b
----

== References

=== Asciidoctor documentations

* https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[AsciiDoc Syntax Quick Reference]
+
This is good for learning AsciiDoc for the first time.

* https://asciidoctor.org/docs/user-manual/[Asciidoctor User Manual]
+
The well-written manual.

* http://www.seinan-gu.ac.jp/~shito/asciidoctor/html_chunk/[Asciidoctor User Manual (unofficial chunked version)]
+
Chunked version of the old manual site generated with https://github.com/wshito/asciidoctor-chunker[asciidoctor-chunker]

=== Alternatives to `adbook`

* https://antora.org/[Antora]
+
A modular documentation site generator. Designed for users of Asciidoctor.

* https://github.com/owenh000/asciidoctor-multipage[asciidoctor-multipage]
+
A multipage HTML converter for Asciidoctor

* https://github.com/wshito/asciidoctor-chunker[asciidoctor-chunker]
+
The utility to create chunked HTML files from the single HTML generated by Asciidoctor.

* Maybe other SSGs such as https://www.mkdocs.org/[MKDocs]

* Maybe org-mode

=== More of AsciiDoc

* https://asciidoctor.org/docs/asciidoctor-revealjs/[asciidoctor-revealjs]
+
Generate html presentations with AsciiDoc and https://revealjs.com/[reveal.js].
+
I made some https://github.com/toyboot4e/presentation_template[template] for it.

