= adbook

== Welcome

`adbook` is a tool for building book-like webpages. If you like this demo, you might like `adbook`, too.

* https://github.com/toyboot4e/adbook[adbook repository]

Scroll right to see a next page; the default theme is using flex layout. I apologize the strange defalt.

=== Installation

==== Rust & adbook

If you have https://play.rust-lang.org/[Rust], `adbook` is available via Crates.io:

[source,bash]
----
$ cargo install adbook # -> $HOME/.cargo/bin
----

==== Ruby & Asciidoctor

You need Ruby and some package manager. I recommend https://rvm.io/[RVM] because programs installed with it ran faster than that were with `rbenv` (somehow).

Then let's get Asciidoctor gems:

[source,bash]
----
$ gem install asciidoctor
$ gem install asciidoctor-diagram
----

We're ready!

== Overview

=== Usage

Let's create a new book:

[source,bash]
----
$ adbook init my-book
Initialized a new adbook project at my-book
----

And see the files in it:

[source,bash]
----
$ tree my-book -L 2
tmp
├── book.ron // <1>
├── site // <2>
└── src // <3>
    ├── article.adoc
    ├── index.adoc
    ├── static
    │   └── img
    ├── index.ron // <4>
    └── theme
        ├── css
        ├── hbs
        └── js

8 directories, 4 files
----
<1> `book.ron` is a base configuration file that maps to https://docs.rs/adbook/latest/adbook/book/config/struct.BookRon.html[BookRon]. https://github.com/ron-rs/ron[Ron] is a human-friendly file format.
<2> `site` is the default html output directory, which can be overridden in `book.ron`.
<3> `src` is the source directory, which is basically mapped to the site directory.
<4> `index.ron` is very similar to `mod.rs` and maps to https://docs.rs/adbook/latest/adbook/book/config/struct.IndexRon.html[IndexRon]. They are located in each directory and lists `.adoc` files in it.

Now we can build our book:

[source,sh]
----
$ cd my-book
$ adbook build
----

For details, check out the https://github.com/toyboot4e/adbook/tree/gh-pages[source files] of this demo.

TODO: serve

=== Differences from mdbook

{adbook} is highly inspired by {mdbook}, but it uses https://asciidoctor.org/docs/what-is-asciidoc/[AsciiDoc] for source files instead of Markdown. AsciiDoc is an expressive language, as you can see in the demos in the next chapter.

Other differences:

* `adbook` uses {prism} by default to highlight source code.
* To be honest, {mdbook} supports a bunch more things:
** Rust Playground
** print view
** search
** dynamic theme change

=== Differences from raw `asciidoctor` command

* `adbook` creates multiple page websites while Asciidoctor creates single page websites by default.

== References

=== Asciidoctor documentations

* https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[AsciiDoc Syntax Quick Reference]
+
This is good for learning AsciiDoc for the first time.

* https://asciidoctor.org/docs/user-manual/[Asciidoctor User Manual]
+
The well-written manual.

* http://www.seinan-gu.ac.jp/~shito/asciidoctor/html_chunk/[Asciidoctor User Manual (unofficial chunked version)]
+
Chunked version of the old manual site generated with https://github.com/wshito/asciidoctor-chunker[asciidoctor-chunker]

=== Alternatives to `adbook`

* https://antora.org/[Antora]
+
A modular documentation site generator. Designed for users of Asciidoctor.

* https://github.com/owenh000/asciidoctor-multipage[asciidoctor-multipage]
+
A multipage HTML converter for Asciidoctor

* https://github.com/wshito/asciidoctor-chunker[asciidoctor-chunker]
+
The utility to create chunked HTML files from the single HTML generated by Asciidoctor.

* Maybe other SSGs such as https://www.mkdocs.org/[MKDocs]

* Maybe org-mode

=== More of AsciiDoc

* https://asciidoctor.org/docs/asciidoctor-revealjs/[asciidoctor-revealjs]
+
Generate html presentations with AsciiDoc and https://revealjs.com/[reveal.js].
+
I made some https://github.com/toyboot4e/presentation_template[template] for it.

