= adbook

`adbook` is a tool for building book-like webpages. If you like this demo, you might like `adbook`, too.

== Installation

=== Rust & adbook

If you have https://play.rust-lang.org/[Rust], `adbook` is available via Crates.io:

[source,bash]
----
$ cargo install adbook # -> $HOME/.cargo/bin
----

=== Ruby & Asciidoctor

You need Ruby and some package manager. I recommend https://rvm.io/[RVM] because programs installed with it runed faster than that were with `rbenv` (somehow).

Then let's get Asciidoctor gems:

[source,bash]
----
$ rvm install asciidoctor
$ rvm install asciidoctor-diagram
----

We're ready!

== Overview

=== Usage

Let's make a new book:

[source,bash]
----
$ adbook init my-book
Initialized a new adbook project at my-book
----

And see the files:

[source,bash]
----
$ tree my-book -L 2
tmp
├── book.ron // <1>
├── site // <2>
└── src // <3>
    ├── article.adoc
    ├── index.adoc
    ├── static
    │   └── img
    ├── theme
    │   ├── css
    │   ├── hbs
    │   └── js
    └── toc.ron // <4>

8 directories, 4 files
----
<1> `book.ron` is a base configuration file that maps to https://docs.rs/adbook/latest/adbook/book/config/struct.BookRon.html[BookRon]
<2> The site directory, where `adbook` outputs files
<3> The source directory, which is basically mapped to the site directory
<4> `toc.ron` is very similar to `mod.rs` and maps to https://docs.rs/adbook/latest/adbook/book/config/struct.TocRon.html[TocRon]. They are located in each directory and lists `.adoc` files in it.

Now we can build our book:

[source,sh]
----
$ cd my-book
$ adbook build
----

`adbook` convertes `.adoc` files to html files using {handlebars} templates.

TODO: serve

=== Differences from mdbook

{adbook} is highly inspired by {mdbook}, but it uses https://asciidoctor.org/docs/what-is-asciidoc/[AsciiDoc] for source files instead of Markdown.

Other differences:

* `adbook` uses {prism} to highlight source files by default.
* `adbook` can't enjoy Rust playground.
* `adbook` doesn't provide hidden source files (so copy some template to get started).

=== Differences from raw `asciidoctor` command

* `adbook` creates multiple page websites while Asciidoctor creates a single page websites by default.
* `adbook` provides some placeholder strings to _document attributes_, such as `{base_url}`.

== References

=== AsciiDoc documentations

* https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[AsciiDoc Syntax Quick Reference]
+
This is good for learning AsciiDoc quickly.

* https://asciidoctor-docs.netlify.app[Asciidoctor Documentation :: The Docs @ Asciidoctor]
+
This is an in-progress official Asciidoctor documentation generated with https://antora.org/[Antora].

* https://asciidoctor.org/docs/user-manual/[Asciidoctor User Manual]
* http://www.seinan-gu.ac.jp/~shito/asciidoctor/html_chunk/[Asciidoctor User Manual (unofficial chunked version)]
+
Generated with https://github.com/wshito/asciidoctor-chunker[asciidoctor-chunker]

=== Alternatives to `adbook`

* https://antora.org/[Antora]
+
A modular documentation site generator. Designed for users of Asciidoctor.

* https://github.com/owenh000/asciidoctor-multipage[asciidoctor-multipage]
+
A multipage HTML converter for Asciidoctor

* https://github.com/wshito/asciidoctor-chunker[asciidoctor-chunker]
+
The utility to create chunked HTML files from the single HTML generated by Asciidoctor.

* Maybe other SSGs
* Maybe org-mode

=== More of AsciiDoc

* https://asciidoctor.org/docs/asciidoctor-revealjs/[asciidoctor-revealjs]
+
Generate html presentations with AsciiDoc and https://revealjs.com/[reveal.js].
+
I made some https://github.com/toyboot4e/presentation_template[template] for it.

